# Generated by Django 5.0.6 on 2024-12-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uiconfiguration',
            table='ui_configuration',
        ),
    ]
