# Generated by Django 5.0.6 on 2024-12-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_workspace_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='alias',
            field=models.CharField(default='Admin', max_length=65, unique=True),
            preserve_default=False,
        ),
    ]
