# Generated by Django 5.0.6 on 2024-12-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_organization_name'),
        ('user_management', 'init_data'),
    ]

    operations = [
    ]
