# Generated by Django 5.0.6 on 2025-01-05 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('user_management', '0003_merge_0002_alter_organization_name_init_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='workspaces',
        ),
        migrations.AlterField(
            model_name='userworkspacerole',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.role'),
        ),
        migrations.CreateModel(
            name='UserAnalysisRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_role',
            },
        ),
    ]
