# Generated by Django 5.0.6 on 2024-12-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_role_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='alias',
            field=models.CharField(default='alias', max_length=65, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
