version: '3'

services:
  users-db:
    image: postgres
    container_name: jaws-users-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:${DATABASE_PORT}
    volumes:
      - users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s

  api:
    container_name: jaws-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8001:8001" #debugpy
    depends_on:
      users-db:
        condition: service_healthy
    volumes:
      - .:/opt/web


volumes: 
  users_data:
