# Generated by Django 5.0.6 on 2024-12-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_notification_mngr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
    ]
