# Generated by Django 5.1.4 on 2025-01-13 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_analysisdataset_alter_analysis_datasets'),
        ('file_management', '0007_dataset_external_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255, null=True)),
                ('x_label', models.CharField(max_length=255, null=True)),
                ('y_label', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie')], default='bar')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_management.dataset')),
                ('x_col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_col', to='file_management.columnconfiguration')),
                ('y_cols', models.ManyToManyField(related_name='y_cols', to='file_management.columnconfiguration')),
            ],
            options={
                'db_table': 'chart',
            },
        ),
    ]
