# Generated by Django 5.1.4 on 2025-01-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add subpillar to charts"""
    dependencies = [
        ("analysis", "0005_add_steps"),
        ("charts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="subpillar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analysis.subpillar",
            ),
        ),
    ]
