# Generated by Django 5.0.6 on 2024-12-11 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaggregation',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'disaggregation',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeDivision',
            fields=[
                ('p_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='P-Code')),
                ('country_code', models.CharField(max_length=255, verbose_name='Country Code')),
                ('admin_level', models.PositiveSmallIntegerField(choices=[(0, 'Country'), (1, 'Province/State'), (2, 'District'), (3, 'City')], verbose_name='Admin Level')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('valid_from_date', models.DateField(null=True, verbose_name='Valid From Date')),
                ('parent_p_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivisions', to='analysis.administrativedivision', verbose_name='Parent P-Code')),
            ],
            options={
                'verbose_name': 'Administrative Division',
                'verbose_name_plural': 'Administrative Divisions',
                'db_table': 'administrative_division',
                'ordering': ['country_code', 'admin_level', 'p_code'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField()),
                ('objectives', models.CharField(max_length=400)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locations', models.ManyToManyField(to='analysis.administrativedivision')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='user_management.workspace')),
                ('disaggregations', models.ManyToManyField(blank=True, to='analysis.disaggregation')),
                ('sectors', models.ManyToManyField(to='analysis.sector')),
            ],
            options={
                'db_table': 'analysis',
            },
        ),
    ]
