# Generated by Django 5.0.6 on 2025-01-05 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_management', '0004_alter_dataset_filename_alter_dataset_size_bytes'),
        ('user_management', '0003_merge_0002_alter_organization_name_init_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'analysis_framework',
            },
        ),
        migrations.CreateModel(
            name='Disaggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'disaggregation',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeDivision',
            fields=[
                ('p_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='P-Code')),
                ('country_code', models.CharField(max_length=255, verbose_name='Country Code')),
                ('admin_level', models.PositiveSmallIntegerField(choices=[(0, 'Country'), (1, 'Province/State'), (2, 'District'), (3, 'City')], verbose_name='Admin Level')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('valid_from_date', models.DateField(null=True, verbose_name='Valid From Date')),
                ('parent_p_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivisions', to='analysis.administrativedivision', verbose_name='Parent P-Code')),
            ],
            options={
                'verbose_name': 'Administrative Division',
                'verbose_name_plural': 'Administrative Divisions',
                'db_table': 'administrative_division',
                'ordering': ['country_code', 'admin_level', 'p_code'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField()),
                ('objectives', models.CharField(max_length=400)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locations', models.ManyToManyField(to='analysis.administrativedivision')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='user_management.workspace')),
            ],
            options={
                'db_table': 'analysis',
            },
        ),
        migrations.CreateModel(
            name='AnalysisDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_management.dataset')),
            ],
            options={
                'db_table': 'analysis_datasets',
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='datasets',
            field=models.ManyToManyField(through='analysis.AnalysisDataset', to='file_management.dataset'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='analysis_framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_framework', to='analysis.analysisframework'),
        ),
        migrations.CreateModel(
            name='AnalysisQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=240)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_questions', to='analysis.analysis')),
            ],
            options={
                'db_table': 'analysis_question',
            },
        ),
        migrations.CreateModel(
            name='AnalysisStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField()),
                ('mandatory', models.BooleanField(default=True)),
                ('step_parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.analysisstep')),
            ],
            options={
                'verbose_name': 'Analysis Step',
                'verbose_name_plural': 'Analyisis Steps',
                'db_table': 'analysis_step',
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='analysis_steps',
            field=models.ManyToManyField(to='analysis.analysisstep'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='disaggregations',
            field=models.ManyToManyField(blank=True, to='analysis.disaggregation'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='sectors',
            field=models.ManyToManyField(to='analysis.sector'),
        ),
    ]
