# Generated by Django 5.1.3 on 2024-12-07 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDivision',
            fields=[
                ('p_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='P-Code')),
                ('country_code', models.CharField(max_length=255, verbose_name='Country Code')),
                ('admin_level', models.PositiveSmallIntegerField(choices=[(0, 'Country'), (1, 'Province/State'), (2, 'District'), (3, 'City')], verbose_name='Admin Level')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('valid_from_date', models.DateField(null=True, verbose_name='Valid From Date')),
                ('parent_p_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivisions', to='analysis.administrativedivision', verbose_name='Parent P-Code')),
            ],
            options={
                'verbose_name': 'Administrative Division',
                'verbose_name_plural': 'Administrative Divisions',
                'db_table': 'administrative_division',
                'ordering': ['country_code', 'admin_level', 'p_code'],
            },
        ),
    ]
