# Generated by Django 5.1.3 on 2024-12-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_administrativedivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='locations',
            field=models.ManyToManyField(to='analysis.administrativedivision'),
        ),
    ]
