# Generated by Django 5.1.4 on 2025-01-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisdataset_alter_analysis_datasets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pillar',
            },
        ),
        migrations.CreateModel(
            name='SubPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sub_pillar',
            },
        ),
        migrations.AddField(
            model_name='analysisframework',
            name='pillars',
            field=models.ManyToManyField(to='analysis.pillar'),
        ),
        migrations.AddField(
            model_name='pillar',
            name='sub_pillars',
            field=models.ManyToManyField(to='analysis.subpillar'),
        ),
    ]
