"""Contains a migration that add initial data"""
# Generated by Django 5.1.3 on 2024-12-11 14:27

import sys
from django.db import migrations, models

from analysis.command.add_administrative_divisions import add_administrative_divisions
from analysis.models.administrative_division import AdministrativeDivision
from analysis.models.disaggregation import Disaggregation
from analysis.models.sector import Sector


def add_disaggregation_data():
    """Add disaggregation data into the Disaggregation model"""
    disaggregations = [
        {"name": "Geography"},
        {"name": "Sex and age"},
        {"name": "Vulnerable Groups"},
        {"name": "Affected Groups"},
    ]
    for disaggregation in disaggregations:
        Disaggregation.objects.create(**disaggregation)


def add_sector_data():
    """Add sectors data into the Sector model"""
    sectors = [
        {"name": "Inter-sectoral"},
        {"name": "Camp Coordination and Camp Management"},
        {"name": "Early Recovery"},
        {"name": "Education"},
        {"name": "Emergency Telecomunications"},
        {"name": "Food Security"},
        {"name": "Health"},
        {"name": "Logistics"},
        {"name": "Nutritions"},
        {"name": "Protection"},
        {"name": "Shelter"},
        {"name": "WASH"},
        {"name": "Cross Cutting Issues"},
        {"name": "Other"},
    ]
    for sector in sectors:
        Sector.objects.create(**sector)

def add_initial_data(apps, schema_editor):
    """Add disaggregations, sectors and administrative divisions"""
    add_disaggregation_data()
    add_sector_data()
    add_administrative_divisions()

def remove_initial_data(apps, schema_editor):
    """Remove disaggregations, sectors and administrative divisions"""
    Sector.objects.all().delete()
    Disaggregation.objects.all().delete()
    AdministrativeDivision.objects.all().delete()


class Migration(migrations.Migration):
    """
    Update ids from Char to autoincremental ID
    """
    dependencies = [
        ("analysis", "0002_alter_analysis_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disaggregation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        )
    ]

    if 'test' not in sys.argv:
        operations.append(migrations.RunPython(add_initial_data, remove_initial_data))
