# Generated by Django 5.1.4 on 2025-01-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_pillar_subpillar_analysisframework_pillars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillar',
            name='alias',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subpillar',
            name='alias',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
