# Generated by Django 5.1.4 on 2025-01-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_pillar_alias_alter_subpillar_alias'),
        ('analysis', 'analysis_framework_pillars_and_sub_pillars_init_data'),
    ]

    operations = [
    ]
