# Generated by Django 5.0.6 on 2025-01-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysis_datasets'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=240)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_questions', to='analysis.analysis')),
            ],
            options={
                'db_table': 'analysis_question',
            },
        ),
    ]
