# Generated by Django 5.0.6 on 2025-01-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_analysisquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'analysis_framework',
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='analysis_framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisframework'),
        ),
        migrations.DeleteModel(
            name='AnalysisQuestion',
        ),
    ]
