# Generated by Django 5.1.4 on 2025-01-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_entry_created_at_entry_fragment_entry_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
