# Generated by Django 5.1.4 on 2024-12-26 19:26

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add Dataset table"""

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True, serialize=False, default=uuid.uuid4
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("url", models.URLField(null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dataset",
                "ordering": ["created_on"],
            },
        ),
    ]
