# Generated by Django 5.1.4 on 2025-01-03 13:12

from django.db import migrations
from django.db.models import OuterRef, Subquery

def remove_duplicates(apps, schema_editor):
    """Remove duplications and left only the last file"""
    Dataset = apps.get_model('file_management', 'Dataset')

    subquery = Dataset.objects.filter(
        filename=OuterRef('filename')
    ).order_by('-created_at').values('id')[:1]

    duplicates = Dataset.objects.exclude(id__in=Subquery(subquery))
    duplicates.delete()

def _(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    """Migrate"""

    dependencies = [
        ('file_management', '0002_alter_dataset_options_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, _)
    ]
