# Generated by Django 5.0.6 on 2025-01-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_alter_dataset_size_bytes'),
        ('file_management', '0004_alter_dataset_filename_alter_dataset_size_bytes'),
    ]

    operations = [
    ]
