# Generated by Django 5.1.4 on 2025-01-04 01:32

import django.db.models.deletion
from django.db import migrations, models

def add_types_and_roles(apps, schema_editor):
    """Add initial data types and data roles"""
    DataType = apps.get_model("file_management", "DataType")
    DataRole = apps.get_model("file_management", "DataRole")

    data_types = [
        "Text",
        "Number",
        "Date",
        "Boolean",
        "Currency",
        "URL",
        "Geo"
    ]

    data_roles = [
        "Unique ID",
        "Admin 0",
        "Admin 1",
        "Admin 2",
        "Gender",
        "Vulnerable Group",
        "Content",
    ]

    for data_type in data_types:
        DataType.objects.create(
            name=data_type
        )

    for data_role in data_roles:
        DataRole.objects.create(
            name=data_role
        )

def remove_types_and_roles(apps, schema_editor):
    """Remove initial data types and data roles"""
    DataType = apps.get_model("file_management", "DataType")
    DataRole = apps.get_model("file_management", "DataRole")

    DataType.objects.all().delete()
    DataRole.object.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ("file_management", "0004_alter_dataset_filename_alter_dataset_size_bytes"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "data_roles",
            },
        ),
        migrations.CreateModel(
            name="DataType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "data_types",
            },
        ),
        migrations.RunPython(add_types_and_roles, remove_types_and_roles),
        migrations.CreateModel(
            name="ColumnConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("include", models.BooleanField(default=True)),
                ("alias", models.CharField(blank=True, max_length=255, null=True)),
                ("last_change", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="file_management.dataset",
                    ),
                ),
                (
                    "data_role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="file_management.datarole",
                    ),
                ),
                (
                    "data_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="file_management.datatype",
                    ),
                ),
            ],
            options={
                "db_table": "column_configurations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "original_name"),
                        name="unique_col_per_dataset",
                    )
                ],
            },
        ),
    ]
