# Generated by Django 5.1.4 on 2025-01-15 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_add_steps'),
        ('file_management', '0007_dataset_external_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnconfiguration',
            name='subpillar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.subpillar'),
        ),
    ]
