name: Development


on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    strategy:
      matrix:
        python-version: ['3.12']

    services:
      users-db: 
        image: postgres
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      analysis-db: 
        image: postgres
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
    - name: Checkout Actions
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under 4 

    - name: Run tests
      env:
        USERS_DATABASE_NAME: test_db
        USERS_DATABASE_USERNAME: test_user
        USERS_DATABASE_HOST: localhost
        USERS_DATABASE_PORT: 5432
        USERS_DATABASE_PASSWORD: test_password
        USERS_DATABASE_ENGINE: django.db.backends.postgresql
        ANALYSIS_DATABASE_NAME: test_db
        ANALYSIS_DATABASE_USERNAME: test_user
        ANALYSIS_DATABASE_HOST: localhost
        ANALYSIS_DATABASE_PORT: 5433
        ANALYSIS_DATABASE_PASSWORD: test_password
        ANALYSIS_DATABASE_ENGINE: django.db.backends.postgresql
      run: |
        python3 manage.py test
